<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<metadata>
    <map>
        <entry>
            <key>DISPLAYNAME</key>
            <value>tosca_ubi_small.yaml</value>
        </entry>
        <entry>
            <key>DATE_MODIFICATION</key>
            <value>1670860917426</value>
        </entry>
        <entry>
            <key>REPOSITORY</key>
            <value>Datafiles</value>
        </entry>
        <entry>
            <key>DATE_CREATION</key>
            <value>1670860917396</value>
        </entry>
        <entry>
            <key>TAG</key>
        </entry>
        <entry>
            <key>FILE_TYPE</key>
            <value>text</value>
        </entry>
        <entry>
            <key>TYPE</key>
            <value>UPLOAD</value>
        </entry>
        <entry>
            <key>COMMENT</key>
        </entry>
    </map>
</metadata>
